module.exports = {
  COMPLAINT: { OPEN: 'OPEN', ASSIGNED: 'ASSIGNED', IN_PROGRESS: 'IN_PROGRESS', RESOLVED: 'RESOLVED', CLOSED: 'CLOSED' },
  QUEUE: { WAITING: 'WAITING', SERVED: 'SERVED', CANCELLED: 'CANCELLED' }
};